version: '3'

services:
  nginx:
    image: nginx:stable-alpine3.17-slim
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - "./app:/var/www"
      - "./docker/nginx:/etc/nginx/conf.d/"
    depends_on:
      - phpapp
    networks:
      - app

  phpapp:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: phpapp
    image: dockerbarn:php8.2-nginx-mysql-pma
    restart: unless-stopped
    tty: true
    working_dir: "/var/www"
    volumes:
      - "./app:/var/www"
    depends_on:
      - mysql
    networks:
      - app

  mysql:
    container_name: mysql
    image: mysql:8
    restart: unless-stopped
    tty: true
    volumes:
      - "./docker/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      PMA_PORT: 3306
      UPLOAD_LIMIT: 300M
    restart: always
    ports:
      - "8080:80"
    networks:
      - app

networks:
  app:
